language: python
python:
    - "3.5"

dist: trusty
sudo: rquired

env:
    matrix:
        -DJANGO_VERSION=1.9.7

install:
    - pip freeze > requirements.txt
    - pip install -r requirements.txt
    - pip install -q Django==$DJANGO_VERSION

script:
    python manage.py test -v 3
      
