# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='_image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='thumb',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
